title:  Redzer Monsod – Cybersecurity Professional Portfolio
description: : Welcome to the professional portfolio of Redzer Monsod. This website showcases my expertise in cybersecurity, including my skills, projects, and accomplishments. The site is designed with the Midnight theme for GitHub Pages, providing a sleek and modern presentation of my wor
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
